[package]
name = "dataflare"
version = "0.1.0"
edition = "2021"
description = "Data integration framework module for Actix"
license = "MIT OR Apache-2.0"
repository = "https://github.com/actix/actix"

[dependencies]
actix = { path = "../actix" }
actix-broker = { path = "../actix-broker" }
actix-cluster = { path = "../actix-cluster" }
actix-rt = "2.9.0"
tokio = { version = "1.35.1", features = ["full"] }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }
csv = "1.3.0"
futures = "0.3.30"
clap = { version = "4.4.11", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
thiserror = "1.0.56"
anyhow = "1.0.79"
log = "0.4.20"
env_logger = "0.10.1"
async-trait = "0.1.77"
chrono = { version = "=0.4.39", features = ["serde"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
lazy_static = "1.4.0"
petgraph = "0.6.4"
tempfile = "3.8.1"
num_cpus = "1.16.0"

[dev-dependencies]
criterion = "0.5.1"
proptest = "1.4.0"
mockall = "0.12.1"
tokio-test = "0.4.3"

# Comentamos los benchmarks por ahora
# [[bench]]
# name = "dataflare_benchmarks"
# harness = false
