version: '3'

services:
  node1:
    build:
      context: ../..
      dockerfile: examples/chat_system/Dockerfile
    container_name: chat-node1
    ports:
      - "8080:8080"
    command: --id node1 --address 0.0.0.0:8080
    networks:
      - chat-network

  node2:
    build:
      context: ../..
      dockerfile: examples/chat_system/Dockerfile
    container_name: chat-node2
    ports:
      - "8081:8080"
    command: --id node2 --address 0.0.0.0:8080 --seed node1:8080
    networks:
      - chat-network
    depends_on:
      - node1

  node3:
    build:
      context: ../..
      dockerfile: examples/chat_system/Dockerfile
    container_name: chat-node3
    ports:
      - "8082:8080"
    command: --id node3 --address 0.0.0.0:8080 --seed node1:8080
    networks:
      - chat-network
    depends_on:
      - node1

networks:
  chat-network:
    driver: bridge 