[workspace]
resolver = "2"
members = [
    "chat_system",
    "task_processor",
    "http_api",
    "file_sync",
    "distributed_benchmark",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75" 